name: Build APK
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install depends
        run: npm i

      - name: Emit autoimport
        run: npm run test src/logic/noop.spec.ts

      - name: Typing
        run: npm run typing

      - name: Test
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.11
          run_install: false

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Install and Build Capacitor 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          pnpm i
          pnpm build:android

      - name: Rename app-release-unsigned.apk to app-release.apk
        run: mv /home/runner/work/app/app/src-capacitor/android/app/build/outputs/apk/release/app-release-unsigned.apk /home/runner/work/app/app/src-capacitor/android/app/build/outputs/apk/release/app-release.apk

      - uses: filippoLeporati93/android-release-signer@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: /home/runner/work/app/app/src-capacitor/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_CONTENT }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## If no one connects after 5 minutes, shut down server.
          wait-timeout-minutes: 5

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@c3f61b2a3db543ceee83c759ac8e48419a1a2211
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: /home/runner/work/app/app/src-capacitor/android/app/build/outputs/apk/release/app-release-signed.apk
          body: ${{ steps.changelog.outputs.changelog }}
