name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Push to branch `release`
        run: |
          git branch release -f
          git push origin release -f

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
