name: Test
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install depends
        run: bun i

      - name: Test
        run: bun run test
